/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILiquidityValueCalculator,
  ILiquidityValueCalculatorInterface,
} from "../ILiquidityValueCalculator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "computeLiquidityShareValue",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenAAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenBAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILiquidityValueCalculator__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidityValueCalculatorInterface {
    return new utils.Interface(_abi) as ILiquidityValueCalculatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiquidityValueCalculator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILiquidityValueCalculator;
  }
}
