/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ILiquidityValueCalculatorContract
  extends Truffle.Contract<ILiquidityValueCalculatorInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<ILiquidityValueCalculatorInstance>;
}

type AllEvents = never;

export interface ILiquidityValueCalculatorInstance
  extends Truffle.ContractInstance {
  computeLiquidityShareValue: {
    (
      liquidity: number | BN | string,
      tokenA: string,
      tokenB: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      liquidity: number | BN | string,
      tokenA: string,
      tokenB: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;
    sendTransaction(
      liquidity: number | BN | string,
      tokenA: string,
      tokenB: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      liquidity: number | BN | string,
      tokenA: string,
      tokenB: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    computeLiquidityShareValue: {
      (
        liquidity: number | BN | string,
        tokenA: string,
        tokenB: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        liquidity: number | BN | string,
        tokenA: string,
        tokenB: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{ 0: BN; 1: BN }>;
      sendTransaction(
        liquidity: number | BN | string,
        tokenA: string,
        tokenB: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        liquidity: number | BN | string,
        tokenA: string,
        tokenB: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
