/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DappCoinTokenContract } from "./DappCoinToken";
import { HackDapperContract } from "./HackDapper";
import { MigrationsContract } from "./Migrations";
import { ReallyValuableTokenContract } from "./ReallyValuableToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DappCoinToken"): DappCoinTokenContract;
      require(name: "HackDapper"): HackDapperContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "ReallyValuableToken"): ReallyValuableTokenContract;
    }
  }
}

export { DappCoinTokenContract, DappCoinTokenInstance } from "./DappCoinToken";
export { HackDapperContract, HackDapperInstance } from "./HackDapper";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  ReallyValuableTokenContract,
  ReallyValuableTokenInstance,
} from "./ReallyValuableToken";
