/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DappCoinTokenContract } from "./DappCoinToken";
import { ERC165Contract } from "./ERC165";
import { ERC20Contract } from "./ERC20";
import { ERC721Contract } from "./ERC721";
import { HackDapperContract } from "./HackDapper";
import { HospoContract } from "./Hospo";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { ISwapRouterContract } from "./ISwapRouter";
import { IUniswapV2FactoryContract } from "./IUniswapV2Factory";
import { IUniswapV2Router01Contract } from "./IUniswapV2Router01";
import { IUniswapV2Router02Contract } from "./IUniswapV2Router02";
import { IUniswapV3SwapCallbackContract } from "./IUniswapV3SwapCallback";
import { OwnableContract } from "./Ownable";
import { ReallyValuableTokenContract } from "./ReallyValuableToken";
import { SimpleSwapContract } from "./SimpleSwap";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DappCoinToken"): DappCoinTokenContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "HackDapper"): HackDapperContract;
      require(name: "Hospo"): HospoContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "ISwapRouter"): ISwapRouterContract;
      require(name: "IUniswapV2Factory"): IUniswapV2FactoryContract;
      require(name: "IUniswapV2Router01"): IUniswapV2Router01Contract;
      require(name: "IUniswapV2Router02"): IUniswapV2Router02Contract;
      require(name: "IUniswapV3SwapCallback"): IUniswapV3SwapCallbackContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "ReallyValuableToken"): ReallyValuableTokenContract;
      require(name: "SimpleSwap"): SimpleSwapContract;
    }
  }
}

export { DappCoinTokenContract, DappCoinTokenInstance } from "./DappCoinToken";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export { HackDapperContract, HackDapperInstance } from "./HackDapper";
export { HospoContract, HospoInstance } from "./Hospo";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { ISwapRouterContract, ISwapRouterInstance } from "./ISwapRouter";
export {
  IUniswapV2FactoryContract,
  IUniswapV2FactoryInstance,
} from "./IUniswapV2Factory";
export {
  IUniswapV2Router01Contract,
  IUniswapV2Router01Instance,
} from "./IUniswapV2Router01";
export {
  IUniswapV2Router02Contract,
  IUniswapV2Router02Instance,
} from "./IUniswapV2Router02";
export {
  IUniswapV3SwapCallbackContract,
  IUniswapV3SwapCallbackInstance,
} from "./IUniswapV3SwapCallback";
export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  ReallyValuableTokenContract,
  ReallyValuableTokenInstance,
} from "./ReallyValuableToken";
export { SimpleSwapContract, SimpleSwapInstance } from "./SimpleSwap";
