/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface SimpleSwapContract
  extends Truffle.Contract<SimpleSwapInstance> {
  "new"(
    _swapRouter: string,
    meta?: Truffle.TransactionDetails
  ): Promise<SimpleSwapInstance>;
}

type AllEvents = never;

export interface SimpleSwapInstance extends Truffle.ContractInstance {
  DAI(txDetails?: Truffle.TransactionDetails): Promise<string>;

  WETH9(txDetails?: Truffle.TransactionDetails): Promise<string>;

  feeTier(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  swapRouter(txDetails?: Truffle.TransactionDetails): Promise<string>;

  swapWETHForDAI: {
    (
      amountIn: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      amountIn: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      amountIn: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      amountIn: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    DAI(txDetails?: Truffle.TransactionDetails): Promise<string>;

    WETH9(txDetails?: Truffle.TransactionDetails): Promise<string>;

    feeTier(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    swapRouter(txDetails?: Truffle.TransactionDetails): Promise<string>;

    swapWETHForDAI: {
      (
        amountIn: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        amountIn: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        amountIn: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        amountIn: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
